version: 1.0.{build}

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
    - master
    - /^backport\/v.*/

skip_tags: true

cache:
  - .targets
  - project\target
  - project\project\target
  - '%localappdata%\coursier'
  - 'C:\Users\appveyor\.sbt'
  - 'C:\Users\appveyor\.ivy2'
  - 'C:\Users\appveyor\.coursier'

environment:
  JAVA_HOME: 'C:\Program Files\Java\jdk1.8.0'
  PATH: '%JAVA_HOME%\bin;%PATH%'

before_build:
  - cmd: 'IF "%APPVEYOR_PULL_REQUEST_NUMBER%"=="" (.\sbt clean)'

build_script:
  - cmd: .\sbt ++"2.11.8" test:compile

test_script:
  - cmd: 'echo mimir = "C:\\Users\\appveyor\\AppData\\Local\\precog" > it\testing.conf'
  - cmd: '.\sbt ++"2.11.8" it/sideEffectTestFSConfig "testOnly -- xonly" "exclusive:testOnly -- xonly"'
