version: '2'
services:
  quasar_mongodb_2_6:
    container_name: quasar_mongodb_2_6
    image: tutum/mongodb:2.6
    command: mongod --smallfiles --noprealloc
    ports:
      - "27018:27017"

  quasar_mongodb_3_0:
    container_name: quasar_mongodb_3_0
    image: mongo:3.0
    command: mongod --smallfiles
    ports:
      - "27019:27017"

  quasar_mongodb_read_only:
    container_name: quasar_mongodb_read_only
    image: mongo:3.0
    command: mongod --smallfiles
    ports:
      - "27020:27017"

  quasar_mongodb_3_2:
    container_name: quasar_mongodb_3_2
    image: mongo:3.2
    command: ["mongod", "--smallfiles", "--storageEngine", "ephemeralForTest"]
    ports:
      - "27021:27017"

  quasar_mongodb_3_4:
    container_name: quasar_mongodb_3_4
    image: mongo:3.4
    command: ["mongod", "--smallfiles", "--storageEngine", "ephemeralForTest"]
    ports:
      - "27022:27017"

  quasar_metastore:
    container_name: quasar_metastore
    image: postgres:9.6.5
    privileged: true
    ports:
      - "5432:5432"

  quasar_marklogic_xml:
    container_name: quasar_marklogic_xml
    build:
      context: ./Dockerfiles/Marklogic
      dockerfile: MarkLogic-Dockerfile
    ports:
      - "8000-8002:8000-8002"
    mem_limit: 2048m

  quasar_marklogic_json:
    container_name: quasar_marklogic_json
    build:
      context: ./Dockerfiles/Marklogic
      dockerfile: MarkLogic-Dockerfile
    ports:
      - "9000-9002:8000-8002"
    mem_limit: 2048m

  quasar_couchbase:
    container_name: quasar_couchbase
    image: couchbase/server:enterprise-4.5.1
    ports:
      - "8091-8094:8091-8094"
      - "11210:11210"
    mem_limit: 2560m

  quasar_spark_cluster:
    container_name: quasar_spark_cluster
    image: slamdata/spark-standalone-cluster:2.2.0
    network_mode: "bridge"
    ports:
      - "8081:8080"
      - "7077:7077"
      - "6066:6066"

  quasar_spark_elasticsearch:
    container_name: quasar_spark_elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.3
    ports:
      - 9200:9200
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
  
  quasar_spark_cassandra:
    container_name: quasar_spark_cassandra
    image: cassandra:3
    #command: /bin/bash -c "sleep 30 && echo ' -- Pausing to let system catch up ... -->' && /docker-entrypoint.sh cassandra -f"
    network_mode: "bridge"
    ports:
      - 7199:7199
      - 9042:9042
      - 9160:9160
      - 7000-7001:7000-7001
  
  quasar_spark_ftp:
    container_name: quasar_spark_ftp
    image: stilliard/pure-ftpd:hardened
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    environment:
      - PUBLICHOST=0.0.0.0
    volumes:
      - ./Dockerfiles/FTP:/etc/pure-ftpd/passwd
  
  quasar_spark_hdfs:
    container_name: quasar_spark_hdfs
    image: slamdata/hadoop-singlenode-cluster:2.7.3
    network_mode: "bridge"
    ports:
      - 8030:8030
      - 8031:8031
      - 8082:8032
      - 8033:8033
      - 8088:8088
      - 9000:9000
      - 10020:10020
      - 19888:19888
      - 50010:50010
      - 50020:50020
      - 50070:50070
      - 50075:50075
      - 50090:50090
